INSERT INTO TB_COUPON_CONFIG (COMPANY_SEQ, ISSUANCE_MAX_COUNT, ISSUANCE_MAX_AMOUNT,
                              ISSUANCE_MAX_VALIDITY, FIXED_USABLE_COUNT, FIXED_ISSUANCE_AMOUNT,
                              MERCHANT_NAME, SEND_COUNT, USE_YN)
VALUES (0, 100, 100000, 30, 1, 10000, '가맹점', 10,
        'Y');

INSERT INTO TB_MEMBER (COMPANY_SEQ, ORGAN_SEQ, AUTH_SEQ, ID, PASSWORD, NAME, PHONE, EMAIL)
VALUES (0, 0, 0, 'ooweat', 'ooweat!@#$', '김태우', '010-0000-0000', 'ooweat@kakao.com');
