CREATE TABLE TB_COUPON_CONFIG
(
    SEQ                   INT AUTO_INCREMENT PRIMARY KEY COMMENT 'SEQ',
    COMPANY_SEQ           MEDIUMINT   NOT NULL COMMENT '소속 SEQ',
    ISSUANCE_MAX_COUNT    SMALLINT    NOT NULL DEFAULT 0 COMMENT '(한달)한도 발권 량: 0=무제한',
    ISSUANCE_MAX_AMOUNT   MEDIUMINT   NOT NULL DEFAULT 0 COMMENT '(한달)한도 발권 금액: 0=무제한',
    ISSUANCE_MAX_VALIDITY INT         NOT NULL DEFAULT 30 COMMENT '유효기간(발급일로부터 +n 일)',
    FIXED_USABLE_COUNT    TINYINT              DEFAULT 1 NOT NULL DEFAULT 1 COMMENT '쿠폰 사용 가능 횟수',
    FIXED_ISSUANCE_AMOUNT MEDIUMINT   NULL COMMENT '쿠폰 발행 고정 금액',
    MERCHANT_NAME         VARCHAR(50) NULL COMMENT '쿠폰에 표기될 사용처 명칭',
    SEND_COUNT            INT                  DEFAULT 0 NOT NULL COMMENT '발송횟수 : n번 ',
    USE_YN                CHAR        NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    CREATE_DATE           DATETIME             DEFAULT CURRENT_TIMESTAMP() NOT NULL COMMENT '등록일',
    MODIFY_DATE           DATETIME    NULL COMMENT '수정일'
)
    COMMENT '쿠폰발행규칙:한도지정' COLLATE = UTF8_UNICODE_CI;

CREATE TABLE TB_MEMBER
(
    SEQ         INT AUTO_INCREMENT COMMENT 'SEQ' PRIMARY KEY COMMENT 'SEQ',
    COMPANY_SEQ MEDIUMINT    NOT NULL COMMENT '소속 SEQ',
    ORGAN_SEQ   MEDIUMINT    NOT NULL COMMENT '조직 SEQ',
    AUTH_SEQ    SMALLINT     NOT NULL COMMENT '권한 SEQ',
    ID          VARCHAR(20)  NOT NULL,
    PASSWORD    VARCHAR(100) NOT NULL,
    NAME        VARCHAR(20)  NOT NULL,
    PHONE       VARCHAR(20)  NULL,
    EMAIL       VARCHAR(50)  NULL,
    USE_YN      CHAR         NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    CREATE_DATE DATETIME              DEFAULT CURRENT_TIMESTAMP() NOT NULL COMMENT '등록일',
    MODIFY_DATE DATETIME     NULL COMMENT '수정일'
)
    COMMENT '사용자' COLLATE = UTF8_UNICODE_CI;
